---

- name: Config as Code for AAP
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_user: admin
    controller_pass: "admin"
    controller_host: "https://localhost"

  tasks:
    # Load credentials from external file
    - name: Bring in credentials variable
      include_vars:
        file: cred.yaml
      run_once: true

    # Manage credentials
    - name: Manage credentials
      ansible.controller.credential:
        controller_host: "https://{{ controller_host }}"
        controller_username: "{{ controller_user }}"
        controller_password: "{{ controller_pass }}"
        name: "{{ item.name }}"
        organization: "{{ item.org }}"
        description: Added by automation
        credential_type: "{{ item.type }}"
        state: "{{ item.state }}"
        inputs:
          password: "{{ item.password }}"
          username: "{{ item.username }}"
        validate_certs: false
      loop: "{{ creds }}"

    # Load inventory variables from external file
    - name: Bring in inventory variables
      include_vars:
        file: inventory.yml
      run_once: true

    # Manage inventories
    - name: Manage inventories
      ansible.controller.inventory:
        controller_host: "https://{{ ansible_host }}"
        controller_username: "{{ controller_user }}"
        controller_password: "{{ controller_pass }}"
        name: "{{ item.name }}"
        description: Added by automation
        state: "{{ item.state }}"
        organization: "{{ item.org }}"
        validate_certs: false
      loop: "{{ inv_var }}"

    # Load inventory source variables from external file
    - name: Bring in inventory source variables
      include_vars:
        file: inventory_source.yml
      run_once: true

    # Manage inventory sources
    - name: Manage inventory sources
      ansible.controller.inventory_source:
        controller_host: "https://{{ ansible_host }}"
        controller_username: "{{ controller_user }}"
        controller_password: "{{ controller_pass }}"
        name: "{{ item.name }}"
        description: Added via automation
        inventory: "{{ item.inventory_name }}"
        credential: "{{ item.inventory_credential }}"
        overwrite: true
        update_on_launch: true
        source: "{{ item.source }}"
        validate_certs: false
      loop: "{{ inv_source }}"
